[package]
name = "dbd-loadout-optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tauri = { version = "2", features = ["fs-all", "http-all"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }